// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaeJh05G84D0l0DptDAzHmlKL8rOqzDXM',
    appId: '1:498630329283:web:ee4397bb314623ca20f376',
    messagingSenderId: '498630329283',
    projectId: 'test-login-4b7e8',
    authDomain: 'test-login-4b7e8.firebaseapp.com',
    storageBucket: 'test-login-4b7e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAiMhebl4gnSeSjAT0wtzFY1Guzkk3Kjs',
    appId: '1:498630329283:android:b004356788d3ffec20f376',
    messagingSenderId: '498630329283',
    projectId: 'test-login-4b7e8',
    storageBucket: 'test-login-4b7e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ7pAgcvmVORGUfGY2K4U7Tn-3VDRtIiY',
    appId: '1:498630329283:ios:a5bb96451a920a6520f376',
    messagingSenderId: '498630329283',
    projectId: 'test-login-4b7e8',
    storageBucket: 'test-login-4b7e8.firebasestorage.app',
    iosBundleId: 'com.example.oscar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ7pAgcvmVORGUfGY2K4U7Tn-3VDRtIiY',
    appId: '1:498630329283:ios:a5bb96451a920a6520f376',
    messagingSenderId: '498630329283',
    projectId: 'test-login-4b7e8',
    storageBucket: 'test-login-4b7e8.firebasestorage.app',
    iosBundleId: 'com.example.oscar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaeJh05G84D0l0DptDAzHmlKL8rOqzDXM',
    appId: '1:498630329283:web:3a6bc895badfd60e20f376',
    messagingSenderId: '498630329283',
    projectId: 'test-login-4b7e8',
    authDomain: 'test-login-4b7e8.firebaseapp.com',
    storageBucket: 'test-login-4b7e8.firebasestorage.app',
  );

}